DROP TABLE T CASCADE CONSTRAINTS;

CREATE TABLE T(A INTEGER, B INTEGER);

GRANT SELECT, UPDATE, INSERT, DELETE ON T TO L3_36;

INSERT INTO T VALUES (0,0);
INSERT INTO T VALUES (2,3);
INSERT INTO T VALUES (0,1);

COMMIT;
